import { describe,it,expect,vi } from 'vitest';
import { answerFromFallback,answerWithSnowflake,createAskHandler } from '../apps/web/lib/server/ask';
import { UNKNOWN } from '../apps/web/lib/server/contracts';
const excerpt={SOURCE_URL:'https://help.openai.com/en/articles/8809935-deleting-and-archiving-chats-in-chatgpt',SOURCE_TITLE:'Deleting chats',CHUNK_TEXT:'You can delete chats in settings.'};
const post=(body:unknown,headers:Record<string,string>={})=>new Request('http://localhost:3000/api/ask',{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
describe('ask a regulatory question',()=>{
 it('grounds live answers in retrieved excerpts and sends only category names',async()=>{const client={search:vi.fn().mockResolvedValue([excerpt]),complete:vi.fn().mockResolvedValue('{"answer":"Delete it in settings.","source_numbers":[1]}')};const a=await answerWithSnowflake({tool:'chatgpt',question:'How do I delete this?',categories:['EMAIL']},client);expect(a).toMatchObject({answer:'Delete it in settings.',source:'snowflake',citations:[{url:excerpt.SOURCE_URL}]});expect(client.complete.mock.calls[0]![0]).toContain('Email address');});
 it('never calls the model without evidence',async()=>{const client={search:vi.fn().mockResolvedValue([]),complete:vi.fn()};expect((await answerWithSnowflake({tool:'claude',question:'What happens to my data?',categories:[]},client)).answer).toBe(UNKNOWN);expect(client.complete).not.toHaveBeenCalled();});
 it('falls back to the closest prewarmed cited answer',()=>{const a=answerFromFallback({tool:'chatgpt',question:'How can I delete my conversations?',categories:[]});expect(a.source).toBe('fallback');expect(a.answer).not.toBe(UNKNOWN);expect(a.citations.length).toBeGreaterThan(0);});
 it('admits when no prewarmed answer matches',()=>{expect(answerFromFallback({tool:'chatgpt',question:'Who founded the company?',categories:[]}).answer).toBe(UNKNOWN);});
 it('validates input, blocks foreign origins, and falls back when Snowflake fails',async()=>{const live=vi.fn().mockRejectedValue(new Error('401'));const h=createAskHandler(live);expect((await h(post({tool:'chatgpt',question:'x'}))).status).toBe(400);expect((await h(post({tool:'chatgpt',question:'What happens?',extra:1}))).status).toBe(400);expect((await h(post({tool:'chatgpt',question:'What happens?',categories:['not a category']}))).status).toBe(400);expect((await h(post({tool:'chatgpt',question:'How do I delete chats?'},{origin:'https://evil.example'}))).status).toBe(403);const res=await h(post({tool:'chatgpt',question:'How do I delete chats?'},{origin:'http://localhost:3000'}));expect(res.status).toBe(200);expect((await res.json()).source).toBe('fallback');});
 it('rate limits bursts',async()=>{let now=0;const h=createAskHandler(async()=>({answer:'a',citations:[],source:'snowflake',generatedAt:''}),answerFromFallback,()=>now);for(let i=0;i<30;i++)expect((await h(post({tool:'gemini',question:'What happens?'}))).status).toBe(200);expect((await h(post({tool:'gemini',question:'What happens?'}))).status).toBe(429);now=60_001;expect((await h(post({tool:'gemini',question:'What happens?'}))).status).toBe(200);});
});
