import { it,expect,vi } from 'vitest';
import { detectFast,PlaceholderMapper } from '@promptshield/engine';
import { prepareFile,type FileGateApi } from '../apps/extension/src/guards/fileGate';
function api(choice:'primary'|'secondary'|'cancel'='primary'):FileGateApi{return {getAdapter:()=>({site:'chatgpt'}),getMapper:vi.fn().mockResolvedValue(new PlaceholderMapper()),saveMapper:vi.fn(),detectWithTimeout:vi.fn(async text=>detectFast(text)),splitForPrompt:vi.fn(async r=>({toAsk:r.findings.filter(f=>!f.allowlisted),allowlisted:r.findings.filter(f=>f.allowlisted)})),openGate:vi.fn().mockResolvedValue(choice),approve:vi.fn(),logEvents:vi.fn(),extractFile:vi.fn(async f=>({status:'ok',text:await f.text()}))};}
it('renames locally to a text file, with no disclosures counted during attachment preparation',async()=>{const a=api();const result=await prepareFile(new File(['demo@example.com'],'resume.pdf'),a);expect(result?.file.name).toBe('resume-redacted.txt');expect(await result?.file.text()).toBe('person_1@example.com');expect(a.logEvents).not.toHaveBeenCalled();await result?.commit();expect(a.saveMapper).toHaveBeenCalled();expect(a.logEvents).not.toHaveBeenCalled();});
it('cancel never approves or logs findings',async()=>{const a=api('cancel');expect(await prepareFile(new File(['demo@example.com'],'resume.txt'),a)).toBe(null);expect(a.approve).not.toHaveBeenCalled();expect(a.logEvents).not.toHaveBeenCalled();});
it('as-is preserves original bytes and commits approval',async()=>{const a=api('secondary');const f=new File(['demo@example.com'],'resume.txt');const result=await prepareFile(f,a);expect(result?.file).toBe(f);await result?.commit();expect(a.approve).toHaveBeenCalled();expect(a.logEvents).not.toHaveBeenCalled();});
it('unreadable files require explicit upload-anyway choice',async()=>{const a=api('primary');a.extractFile=vi.fn().mockResolvedValue({status:'unsupported',reason:'Image'});expect(await prepareFile(new File(['image'],'image.png'),a)).toBe(null);expect(a.openGate).toHaveBeenCalledWith(expect.objectContaining({mode:'cant_check'}));});
it('scan failure is never treated as clean',async()=>{const a=api('cancel');a.detectWithTimeout=vi.fn().mockRejectedValue(new Error('private'));await expect(prepareFile(new File(['demo@example.com'],'resume.txt'),a)).rejects.toThrow();expect(a.approve).not.toHaveBeenCalled();});
