import { useEffect,useState } from 'react';
import { createRoot } from 'react-dom/client';
import { DEFAULT_SETTINGS,EXPLANATIONS,type Settings,type UserTerms } from '@promptshield/engine';
import { Shell } from '../../src/shared-ui/components';
import { sites,siteNames,types,splitTerms,normalizeSettings } from '../../src/shared-ui/data';
import { useLocalData,writeLocal } from '../../src/shared-ui/storage';
import '../../src/shared-ui/style.css';
const fields:{key:keyof UserTerms;label:string;placeholder:string}[]=[{key:'names',label:'Names',placeholder:'Your name, another spelling'},{key:'emails',label:'Email addresses',placeholder:'you@example.com'},{key:'phones',label:'Phone numbers',placeholder:'Your phone numbers'},{key:'addresses',label:'Addresses',placeholder:'Your home or work address'},{key:'custom',label:'Custom private words',placeholder:'Project names, private identifiers'}];
function SettingsPage(){
 const {settings,loading,error}=useLocalData();const [draft,setDraft]=useState<Settings>(structuredClone(DEFAULT_SETTINGS));const [terms,setTerms]=useState<Record<keyof UserTerms,string>>({names:'',emails:'',phones:'',addresses:'',custom:''});const [dirty,setDirty]=useState(false);const [allow,setAllow]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 const signature=JSON.stringify(settings);
 useEffect(()=>{if(!loading&&!dirty){setDraft(settings);setTerms(Object.fromEntries(fields.map(f=>[f.key,settings.userTerms[f.key].join(', ')])) as Record<keyof UserTerms,string>);}},[signature,loading,dirty]);
 function update(value:Partial<Settings>){setDraft(d=>({...d,...value}));setDirty(true);setMessage('');}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage('');const userTerms=Object.fromEntries(fields.map(f=>[f.key,splitTerms(terms[f.key])])) as unknown as UserTerms;try{await writeLocal({settings:normalizeSettings({...draft,userTerms})});setDirty(false);setMessage('Saved on this device.');}catch{setMessage('Could not save. Your edits are still here; try again.');}finally{setSaving(false);}}
 function add(){const value=allow.trim();if(!value)return;update({allowlist:[...new Set([...draft.allowlist,value])]});setAllow('');}
 return <Shell page="options"><header className="heading"><div><div className="eyebrow">MAKE IT YOURS</div><h1>Your privacy preferences.</h1><p>You decide what stays private and what can pass through.</p></div><span className="pill">Stored only on this device</span></header>{error&&<div className="error" role="alert">{error}</div>}{loading?<div className="empty">Loading your preferences…</div>:<form onSubmit={e=>void save(e)}><section className="card form-section"><h2>Your details</h2><p>Stored only on this device. Helps the shared detector recognize your own details. Separate entries with commas.</p><div className="field-grid">{fields.map(f=><div className="field" key={f.key}><label htmlFor={f.key}>{f.label}</label><input id={f.key} type="text" autoComplete="off" value={terms[f.key]} placeholder={f.placeholder} onChange={e=>{setTerms(t=>({...t,[f.key]:e.target.value}));setDirty(true);setMessage('');}}/></div>)}</div><p style={{fontSize:11,marginTop:12}}>Detection support depends on the shared engine. It currently detects emails only.</p></section><section className="card form-section"><h2>Always allow</h2><p>These values are never asked about when guards are connected.</p><div className="allow-row"><input type="text" aria-label="Value to always allow" placeholder="A value you’re comfortable sharing" value={allow} onChange={e=>setAllow(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add();}}}/><button type="button" className="btn" onClick={add}>Add</button></div><div className="allow-list">{draft.allowlist.map(value=><span className="pill" key={value}>{value}<button type="button" aria-label={`Remove ${value}`} onClick={()=>update({allowlist:draft.allowlist.filter(v=>v!==value)})}>×</button></span>)}</div></section><section className="card form-section"><h2>Detection types</h2><p>Choose which kinds of information the detector checks.</p><div className="checks">{types.map(type=><label className="check" key={type}><input type="checkbox" checked={draft.enabledTypes.includes(type)} onChange={e=>update({enabledTypes:e.target.checked?[...draft.enabledTypes,type]:draft.enabledTypes.filter(t=>t!==type)})}/>{EXPLANATIONS[type].label}</label>)}</div></section><section className="card form-section"><h2>AI tools</h2><p>Enable or pause protection for each supported site.</p><div className="checks">{sites.map(site=><label className="check" key={site}><input type="checkbox" checked={draft.sites.includes(site)} onChange={e=>update({sites:e.target.checked?[...draft.sites,site]:draft.sites.filter(s=>s!==site)})}/>{siteNames[site]}</label>)}</div></section><div className="actions"><button className="btn btn-primary" type="submit" disabled={saving}>{saving?'Saving…':'Save preferences'}</button>{message&&<span role="status" className={message.startsWith('Saved')?'success':'error'}>{message}</span>}</div></form>}</Shell>;
}
createRoot(document.getElementById('root')!).render(<SettingsPage/>);
