-- Run AFTER loading the reviewed knowledge base. This creates a billable search service.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE PS_WH;
ALTER TABLE PROMPTSHIELD.KB.POLICY_CHUNKS SET CHANGE_TRACKING=TRUE;
CREATE CORTEX SEARCH SERVICE IF NOT EXISTS PROMPTSHIELD.KB.POLICY_SEARCH
 ON CHUNK_TEXT ATTRIBUTES TOOL_ID
 WAREHOUSE=PS_WH TARGET_LAG='1 day'
 AS SELECT CHUNK_TEXT, TOOL_ID, TOOL_NAME, SOURCE_URL, SOURCE_TITLE
 FROM PROMPTSHIELD.KB.POLICY_CHUNKS;
GRANT USAGE ON CORTEX SEARCH SERVICE PROMPTSHIELD.KB.POLICY_SEARCH TO ROLE PROMPTSHIELD_APP;
SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW('PROMPTSHIELD.KB.POLICY_SEARCH',
 '{"query":"are conversations used for training","columns":["CHUNK_TEXT","SOURCE_URL"],"filter":{"@eq":{"TOOL_ID":"chatgpt"}},"limit":4}');
-- When the hackathon is over, suspend service compute if no longer needed:
-- ALTER CORTEX SEARCH SERVICE PROMPTSHIELD.KB.POLICY_SEARCH SUSPEND SERVING;
-- ALTER CORTEX SEARCH SERVICE PROMPTSHIELD.KB.POLICY_SEARCH SUSPEND INDEXING;

-- After re-running load_kb.py --upload (e.g. when new tools are added), refresh
-- now instead of waiting up to TARGET_LAG, then prewarm the fixtures:
-- ALTER CORTEX SEARCH SERVICE PROMPTSHIELD.KB.POLICY_SEARCH REFRESH;
