"""Dry-run by default. Upload only reviewed public policy text; never user content."""
import argparse
import json
import os
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
TOOLS = {"chatgpt":"ChatGPT","claude":"Claude","gemini":"Gemini","copilot":"Copilot","perplexity":"Perplexity","deepseek":"DeepSeek","meta_ai":"Meta AI","grammarly":"Grammarly"}
DOMAINS = {"chatgpt":["openai.com"],"claude":["anthropic.com","claude.com"],"gemini":["google.com"],"copilot":["microsoft.com"],"perplexity":["perplexity.ai"],"deepseek":["deepseek.com"],"meta_ai":["meta.com","facebook.com","whatsapp.com"],"grammarly":["grammarly.com","superhuman.com"]}

def chunk_text(text, size=1200, overlap=200):
    if size <= overlap or overlap < 0:
        raise ValueError("Chunk size must exceed a nonnegative overlap")
    text = text.strip()
    start = 0
    while start < len(text):
        end = min(start + size, len(text))
        if end < len(text):
            split = text.rfind("\n\n", start + size // 2, end)
            if split > start:
                end = split
        chunk = text[start:end].strip()
        if chunk:
            yield chunk
        if end == len(text):
            break
        start = max(start + 1, end - overlap)

def collect(root):
    rows = []
    for path in sorted(root.glob("*/*.txt")):
        tool = path.parent.name
        if tool not in TOOLS:
            raise ValueError("Unknown tool directory")
        lines = path.read_text(encoding="utf-8").splitlines()
        if len(lines) < 3 or not lines[0].startswith("URL: ") or not lines[1].startswith("TITLE: "):
            raise ValueError("Every policy file needs URL and TITLE header lines")
        url, title = lines[0][5:].strip(), lines[1][7:].strip()
        parsed = urlparse(url)
        if parsed.scheme != "https" or not any(parsed.hostname == d or (parsed.hostname or "").endswith("."+d) for d in DOMAINS[tool]):
            raise ValueError("Policy URL must be an official HTTPS source for this tool")
        body = "\n".join(lines[2:]).strip()
        if not title or not body:
            raise ValueError("Empty policy source")
        for chunk in chunk_text(body):
            rows.append(dict(TOOL_ID=tool,TOOL_NAME=TOOLS[tool],SOURCE_URL=url,SOURCE_TITLE=title,CHUNK_TEXT=chunk))
    return rows

def sql_literal(value):
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"

def to_sql(rows, batch=40):
    cols = ["TOOL_ID","TOOL_NAME","SOURCE_URL","SOURCE_TITLE","CHUNK_TEXT"]
    out = ["-- Generated by load_kb.py --sql from reviewed public policy text. Replaces all rows.",
           "USE ROLE ACCOUNTADMIN;", "USE WAREHOUSE PS_WH;", "BEGIN;",
           "DELETE FROM PROMPTSHIELD.KB.POLICY_CHUNKS;"]
    for i in range(0, len(rows), batch):
        values = ",\n".join("(" + ", ".join(sql_literal(r[c]) for c in cols) + ")" for r in rows[i:i+batch])
        out.append(f"INSERT INTO PROMPTSHIELD.KB.POLICY_CHUNKS ({', '.join(cols)}) VALUES\n{values};")
    out += ["COMMIT;", "SELECT TOOL_ID, COUNT(*) AS CHUNKS FROM PROMPTSHIELD.KB.POLICY_CHUNKS GROUP BY 1 ORDER BY 1;"]
    return "\n".join(out) + "\n"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--upload", action="store_true", help="Replace the policy table with the reviewed local corpus")
    parser.add_argument("--sql", type=Path, help="Write a Snowsight-ready SQL script that replaces the table (no connector or SSO needed)")
    parser.add_argument("--kb", type=Path, default=ROOT/"snowflake/kb")
    args = parser.parse_args()
    rows = collect(args.kb)
    if not rows:
        raise SystemExit("No policy text found; nothing was uploaded")
    print(json.dumps({"chunks":len(rows),"tools":sorted({r["TOOL_ID"] for r in rows}),"mode":"upload" if args.upload else "sql" if args.sql else "dry-run"}))
    if args.sql:
        args.sql.write_text(to_sql(rows), encoding="utf-8")
        print(f"Wrote {args.sql}; paste it into a Snowsight worksheet and Run All")
        return
    if not args.upload:
        return
    from dotenv import load_dotenv
    import pandas as pd
    import snowflake.connector
    from snowflake.connector.pandas_tools import write_pandas
    load_dotenv(ROOT/"apps/web/.env.local")
    # Browser SSO keeps ingestion/admin credentials out of the API token.
    account = os.environ.get("SNOWFLAKE_ACCOUNT") or urlparse(os.environ["SNOWFLAKE_ACCOUNT_URL"]).hostname.removesuffix(".snowflakecomputing.com")
    user = os.environ.get("SNOWFLAKE_USER")
    if not user:
        raise SystemExit("Set SNOWFLAKE_USER locally for browser-based loader sign-in")
    with snowflake.connector.connect(account=account,user=user,authenticator="externalbrowser",role=os.environ.get("SNOWFLAKE_LOAD_ROLE","ACCOUNTADMIN"),warehouse="PS_WH",database="PROMPTSHIELD",schema="KB") as conn:
        # overwrite with auto_create_table=False truncates/reloads, preserving grants.
        success, _, count, _ = write_pandas(conn,pd.DataFrame(rows),"POLICY_CHUNKS",database="PROMPTSHIELD",schema="KB",overwrite=True,auto_create_table=False)
        if not success or count != len(rows):
            raise SystemExit("Load was incomplete; inspect the table before prewarming")
        conn.cursor().execute("ALTER TABLE PROMPTSHIELD.KB.POLICY_CHUNKS SET CHANGE_TRACKING=TRUE")
        print(f"Loaded {count} public policy chunks")

if __name__ == "__main__":
    main()
