-- Already run successfully in your account. Safe to repeat; preserves rows.
USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS PS_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;
CREATE DATABASE IF NOT EXISTS PROMPTSHIELD;
CREATE SCHEMA IF NOT EXISTS PROMPTSHIELD.KB;
CREATE TABLE IF NOT EXISTS PROMPTSHIELD.KB.POLICY_CHUNKS (
 TOOL_ID STRING, TOOL_NAME STRING, SOURCE_URL STRING, SOURCE_TITLE STRING, CHUNK_TEXT STRING
);
ALTER TABLE PROMPTSHIELD.KB.POLICY_CHUNKS SET CHANGE_TRACKING=TRUE;
